{% set name = "deep-labelprop" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deep-labelprop-{{ version }}.tar.gz
  sha256: 8618f61d61a615ffb7bc43a9bb642551ebe286d5dea4f5bcce45db772bb111bf

build:
  entry_points:
    - labelprop = labelprop.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - flask >=2.1.0
    - kornia >=0.6.12
    - lightning
    - monai <=1.1
    - nibabel >=3.2.1
    - numpy
    - plotext >=4.2.0
    - python >=3.8

test:
  imports:
    - labelprop
  commands:
    - pip list
    # - pip check  # Fails due to relaxed constraints. Uncomment on next release
    - labelprop --help
  requires:
    - pip

about:
  home: https://github.com/nathandecaux/labelprop
  summary: Label propagation using deep registration
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - nathandecaux
